//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenTrustedIpsInitParameters) DeepCopyInto(out *AccessTokenTrustedIpsInitParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenTrustedIpsInitParameters.
func (in *AccessTokenTrustedIpsInitParameters) DeepCopy() *AccessTokenTrustedIpsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccessTokenTrustedIpsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenTrustedIpsObservation) DeepCopyInto(out *AccessTokenTrustedIpsObservation) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenTrustedIpsObservation.
func (in *AccessTokenTrustedIpsObservation) DeepCopy() *AccessTokenTrustedIpsObservation {
	if in == nil {
		return nil
	}
	out := new(AccessTokenTrustedIpsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenTrustedIpsParameters) DeepCopyInto(out *AccessTokenTrustedIpsParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenTrustedIpsParameters.
func (in *AccessTokenTrustedIpsParameters) DeepCopy() *AccessTokenTrustedIpsParameters {
	if in == nil {
		return nil
	}
	out := new(AccessTokenTrustedIpsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSecretTrustedIpsInitParameters) DeepCopyInto(out *ClientSecretTrustedIpsInitParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSecretTrustedIpsInitParameters.
func (in *ClientSecretTrustedIpsInitParameters) DeepCopy() *ClientSecretTrustedIpsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClientSecretTrustedIpsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSecretTrustedIpsObservation) DeepCopyInto(out *ClientSecretTrustedIpsObservation) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSecretTrustedIpsObservation.
func (in *ClientSecretTrustedIpsObservation) DeepCopy() *ClientSecretTrustedIpsObservation {
	if in == nil {
		return nil
	}
	out := new(ClientSecretTrustedIpsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSecretTrustedIpsParameters) DeepCopyInto(out *ClientSecretTrustedIpsParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSecretTrustedIpsParameters.
func (in *ClientSecretTrustedIpsParameters) DeepCopy() *ClientSecretTrustedIpsParameters {
	if in == nil {
		return nil
	}
	out := new(ClientSecretTrustedIpsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Identity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityInitParameters) DeepCopyInto(out *IdentityInitParameters) {
	*out = *in
	if in.HasDeleteProtection != nil {
		in, out := &in.HasDeleteProtection, &out.HasDeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityInitParameters.
func (in *IdentityInitParameters) DeepCopy() *IdentityInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuth) DeepCopyInto(out *IdentityKubernetesAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuth.
func (in *IdentityKubernetesAuth) DeepCopy() *IdentityKubernetesAuth {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityKubernetesAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthInitParameters) DeepCopyInto(out *IdentityKubernetesAuthInitParameters) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]AccessTokenTrustedIpsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedAudience != nil {
		in, out := &in.AllowedAudience, &out.AllowedAudience
		*out = new(string)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedServiceAccountNames != nil {
		in, out := &in.AllowedServiceAccountNames, &out.AllowedServiceAccountNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GatewayID != nil {
		in, out := &in.GatewayID, &out.GatewayID
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesCACertificate != nil {
		in, out := &in.KubernetesCACertificate, &out.KubernetesCACertificate
		*out = new(string)
		**out = **in
	}
	if in.KubernetesHost != nil {
		in, out := &in.KubernetesHost, &out.KubernetesHost
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerJwt != nil {
		in, out := &in.TokenReviewerJwt, &out.TokenReviewerJwt
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerMode != nil {
		in, out := &in.TokenReviewerMode, &out.TokenReviewerMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthInitParameters.
func (in *IdentityKubernetesAuthInitParameters) DeepCopy() *IdentityKubernetesAuthInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthList) DeepCopyInto(out *IdentityKubernetesAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityKubernetesAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthList.
func (in *IdentityKubernetesAuthList) DeepCopy() *IdentityKubernetesAuthList {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityKubernetesAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthObservation) DeepCopyInto(out *IdentityKubernetesAuthObservation) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]AccessTokenTrustedIpsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedAudience != nil {
		in, out := &in.AllowedAudience, &out.AllowedAudience
		*out = new(string)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedServiceAccountNames != nil {
		in, out := &in.AllowedServiceAccountNames, &out.AllowedServiceAccountNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GatewayID != nil {
		in, out := &in.GatewayID, &out.GatewayID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.KubernetesCACertificate != nil {
		in, out := &in.KubernetesCACertificate, &out.KubernetesCACertificate
		*out = new(string)
		**out = **in
	}
	if in.KubernetesHost != nil {
		in, out := &in.KubernetesHost, &out.KubernetesHost
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerJwt != nil {
		in, out := &in.TokenReviewerJwt, &out.TokenReviewerJwt
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerMode != nil {
		in, out := &in.TokenReviewerMode, &out.TokenReviewerMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthObservation.
func (in *IdentityKubernetesAuthObservation) DeepCopy() *IdentityKubernetesAuthObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthParameters) DeepCopyInto(out *IdentityKubernetesAuthParameters) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]AccessTokenTrustedIpsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedAudience != nil {
		in, out := &in.AllowedAudience, &out.AllowedAudience
		*out = new(string)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedServiceAccountNames != nil {
		in, out := &in.AllowedServiceAccountNames, &out.AllowedServiceAccountNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GatewayID != nil {
		in, out := &in.GatewayID, &out.GatewayID
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesCACertificate != nil {
		in, out := &in.KubernetesCACertificate, &out.KubernetesCACertificate
		*out = new(string)
		**out = **in
	}
	if in.KubernetesHost != nil {
		in, out := &in.KubernetesHost, &out.KubernetesHost
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerJwt != nil {
		in, out := &in.TokenReviewerJwt, &out.TokenReviewerJwt
		*out = new(string)
		**out = **in
	}
	if in.TokenReviewerMode != nil {
		in, out := &in.TokenReviewerMode, &out.TokenReviewerMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthParameters.
func (in *IdentityKubernetesAuthParameters) DeepCopy() *IdentityKubernetesAuthParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthSpec) DeepCopyInto(out *IdentityKubernetesAuthSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthSpec.
func (in *IdentityKubernetesAuthSpec) DeepCopy() *IdentityKubernetesAuthSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityKubernetesAuthStatus) DeepCopyInto(out *IdentityKubernetesAuthStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityKubernetesAuthStatus.
func (in *IdentityKubernetesAuthStatus) DeepCopy() *IdentityKubernetesAuthStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityKubernetesAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityList) DeepCopyInto(out *IdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Identity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityList.
func (in *IdentityList) DeepCopy() *IdentityList {
	if in == nil {
		return nil
	}
	out := new(IdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityObservation) DeepCopyInto(out *IdentityObservation) {
	*out = *in
	if in.AuthModes != nil {
		in, out := &in.AuthModes, &out.AuthModes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.HasDeleteProtection != nil {
		in, out := &in.HasDeleteProtection, &out.HasDeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityObservation.
func (in *IdentityObservation) DeepCopy() *IdentityObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityParameters) DeepCopyInto(out *IdentityParameters) {
	*out = *in
	if in.HasDeleteProtection != nil {
		in, out := &in.HasDeleteProtection, &out.HasDeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityParameters.
func (in *IdentityParameters) DeepCopy() *IdentityParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySpec) DeepCopyInto(out *IdentitySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySpec.
func (in *IdentitySpec) DeepCopy() *IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityStatus) DeepCopyInto(out *IdentityStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityStatus.
func (in *IdentityStatus) DeepCopy() *IdentityStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuth) DeepCopyInto(out *IdentityUniversalAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuth.
func (in *IdentityUniversalAuth) DeepCopy() *IdentityUniversalAuth {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityUniversalAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsInitParameters) DeepCopyInto(out *IdentityUniversalAuthAccessTokenTrustedIpsInitParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthAccessTokenTrustedIpsInitParameters.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsInitParameters) DeepCopy() *IdentityUniversalAuthAccessTokenTrustedIpsInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthAccessTokenTrustedIpsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsObservation) DeepCopyInto(out *IdentityUniversalAuthAccessTokenTrustedIpsObservation) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthAccessTokenTrustedIpsObservation.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsObservation) DeepCopy() *IdentityUniversalAuthAccessTokenTrustedIpsObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthAccessTokenTrustedIpsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsParameters) DeepCopyInto(out *IdentityUniversalAuthAccessTokenTrustedIpsParameters) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthAccessTokenTrustedIpsParameters.
func (in *IdentityUniversalAuthAccessTokenTrustedIpsParameters) DeepCopy() *IdentityUniversalAuthAccessTokenTrustedIpsParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthAccessTokenTrustedIpsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecret) DeepCopyInto(out *IdentityUniversalAuthClientSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecret.
func (in *IdentityUniversalAuthClientSecret) DeepCopy() *IdentityUniversalAuthClientSecret {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityUniversalAuthClientSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretInitParameters) DeepCopyInto(out *IdentityUniversalAuthClientSecretInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NumberOfUsesLimit != nil {
		in, out := &in.NumberOfUsesLimit, &out.NumberOfUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretInitParameters.
func (in *IdentityUniversalAuthClientSecretInitParameters) DeepCopy() *IdentityUniversalAuthClientSecretInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretList) DeepCopyInto(out *IdentityUniversalAuthClientSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityUniversalAuthClientSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretList.
func (in *IdentityUniversalAuthClientSecretList) DeepCopy() *IdentityUniversalAuthClientSecretList {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityUniversalAuthClientSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretObservation) DeepCopyInto(out *IdentityUniversalAuthClientSecretObservation) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IsRevoked != nil {
		in, out := &in.IsRevoked, &out.IsRevoked
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfUses != nil {
		in, out := &in.NumberOfUses, &out.NumberOfUses
		*out = new(float64)
		**out = **in
	}
	if in.NumberOfUsesLimit != nil {
		in, out := &in.NumberOfUsesLimit, &out.NumberOfUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretObservation.
func (in *IdentityUniversalAuthClientSecretObservation) DeepCopy() *IdentityUniversalAuthClientSecretObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretParameters) DeepCopyInto(out *IdentityUniversalAuthClientSecretParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NumberOfUsesLimit != nil {
		in, out := &in.NumberOfUsesLimit, &out.NumberOfUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretParameters.
func (in *IdentityUniversalAuthClientSecretParameters) DeepCopy() *IdentityUniversalAuthClientSecretParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretSpec) DeepCopyInto(out *IdentityUniversalAuthClientSecretSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretSpec.
func (in *IdentityUniversalAuthClientSecretSpec) DeepCopy() *IdentityUniversalAuthClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthClientSecretStatus) DeepCopyInto(out *IdentityUniversalAuthClientSecretStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthClientSecretStatus.
func (in *IdentityUniversalAuthClientSecretStatus) DeepCopy() *IdentityUniversalAuthClientSecretStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthClientSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthInitParameters) DeepCopyInto(out *IdentityUniversalAuthInitParameters) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]IdentityUniversalAuthAccessTokenTrustedIpsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretTrustedIps != nil {
		in, out := &in.ClientSecretTrustedIps, &out.ClientSecretTrustedIps
		*out = make([]ClientSecretTrustedIpsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthInitParameters.
func (in *IdentityUniversalAuthInitParameters) DeepCopy() *IdentityUniversalAuthInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthList) DeepCopyInto(out *IdentityUniversalAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityUniversalAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthList.
func (in *IdentityUniversalAuthList) DeepCopy() *IdentityUniversalAuthList {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityUniversalAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthObservation) DeepCopyInto(out *IdentityUniversalAuthObservation) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]IdentityUniversalAuthAccessTokenTrustedIpsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretTrustedIps != nil {
		in, out := &in.ClientSecretTrustedIps, &out.ClientSecretTrustedIps
		*out = make([]ClientSecretTrustedIpsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthObservation.
func (in *IdentityUniversalAuthObservation) DeepCopy() *IdentityUniversalAuthObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthParameters) DeepCopyInto(out *IdentityUniversalAuthParameters) {
	*out = *in
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(float64)
		**out = **in
	}
	if in.AccessTokenTrustedIps != nil {
		in, out := &in.AccessTokenTrustedIps, &out.AccessTokenTrustedIps
		*out = make([]IdentityUniversalAuthAccessTokenTrustedIpsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretTrustedIps != nil {
		in, out := &in.ClientSecretTrustedIps, &out.ClientSecretTrustedIps
		*out = make([]ClientSecretTrustedIpsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdentityID != nil {
		in, out := &in.IdentityID, &out.IdentityID
		*out = new(string)
		**out = **in
	}
	if in.IdentityIDRef != nil {
		in, out := &in.IdentityIDRef, &out.IdentityIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityIDSelector != nil {
		in, out := &in.IdentityIDSelector, &out.IdentityIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthParameters.
func (in *IdentityUniversalAuthParameters) DeepCopy() *IdentityUniversalAuthParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthSpec) DeepCopyInto(out *IdentityUniversalAuthSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthSpec.
func (in *IdentityUniversalAuthSpec) DeepCopy() *IdentityUniversalAuthSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityUniversalAuthStatus) DeepCopyInto(out *IdentityUniversalAuthStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityUniversalAuthStatus.
func (in *IdentityUniversalAuthStatus) DeepCopy() *IdentityUniversalAuthStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityUniversalAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataInitParameters) DeepCopyInto(out *MetadataInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataInitParameters.
func (in *MetadataInitParameters) DeepCopy() *MetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataObservation) DeepCopyInto(out *MetadataObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataObservation.
func (in *MetadataObservation) DeepCopy() *MetadataObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataParameters) DeepCopyInto(out *MetadataParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataParameters.
func (in *MetadataParameters) DeepCopy() *MetadataParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataParameters)
	in.DeepCopyInto(out)
	return out
}
