// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this IdentityKubernetesAuth.
func (mg *IdentityKubernetesAuth) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IdentityIDRef,
		Selector:     mg.Spec.ForProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IdentityID")
	}
	mg.Spec.ForProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IdentityIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IdentityIDRef,
		Selector:     mg.Spec.InitProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IdentityID")
	}
	mg.Spec.InitProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IdentityIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IdentityUniversalAuth.
func (mg *IdentityUniversalAuth) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IdentityIDRef,
		Selector:     mg.Spec.ForProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IdentityID")
	}
	mg.Spec.ForProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IdentityIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IdentityIDRef,
		Selector:     mg.Spec.InitProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IdentityID")
	}
	mg.Spec.InitProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IdentityIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IdentityUniversalAuthClientSecret.
func (mg *IdentityUniversalAuthClientSecret) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IdentityIDRef,
		Selector:     mg.Spec.ForProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IdentityID")
	}
	mg.Spec.ForProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IdentityIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentityID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IdentityIDRef,
		Selector:     mg.Spec.InitProvider.IdentityIDSelector,
		To: reference.To{
			List:    &IdentityList{},
			Managed: &Identity{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IdentityID")
	}
	mg.Spec.InitProvider.IdentityID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IdentityIDRef = rsp.ResolvedReference

	return nil
}
