// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClientSecretTrustedIpsInitParameters struct {
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type ClientSecretTrustedIpsObservation struct {
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type ClientSecretTrustedIpsParameters struct {

	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type IdentityUniversalAuthAccessTokenTrustedIpsInitParameters struct {
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type IdentityUniversalAuthAccessTokenTrustedIpsObservation struct {
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type IdentityUniversalAuthAccessTokenTrustedIpsParameters struct {

	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type IdentityUniversalAuthInitParameters struct {

	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	AccessTokenTrustedIps []IdentityUniversalAuthAccessTokenTrustedIpsInitParameters `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	ClientSecretTrustedIps []ClientSecretTrustedIpsInitParameters `json:"clientSecretTrustedIps,omitempty" tf:"client_secret_trusted_ips,omitempty"`

	// The ID of the identity to attach the configuration onto.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`
}

type IdentityUniversalAuthObservation struct {

	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	AccessTokenTrustedIps []IdentityUniversalAuthAccessTokenTrustedIpsObservation `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	ClientSecretTrustedIps []ClientSecretTrustedIpsObservation `json:"clientSecretTrustedIps,omitempty" tf:"client_secret_trusted_ips,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the identity to attach the configuration onto.
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`
}

type IdentityUniversalAuthParameters struct {

	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// +kubebuilder:validation:Optional
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	// +kubebuilder:validation:Optional
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// +kubebuilder:validation:Optional
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// +kubebuilder:validation:Optional
	AccessTokenTrustedIps []IdentityUniversalAuthAccessTokenTrustedIpsParameters `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	// +kubebuilder:validation:Optional
	ClientSecretTrustedIps []ClientSecretTrustedIpsParameters `json:"clientSecretTrustedIps,omitempty" tf:"client_secret_trusted_ips,omitempty"`

	// The ID of the identity to attach the configuration onto.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	// +kubebuilder:validation:Optional
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`
}

// IdentityUniversalAuthSpec defines the desired state of IdentityUniversalAuth
type IdentityUniversalAuthSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IdentityUniversalAuthParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityUniversalAuthInitParameters `json:"initProvider,omitempty"`
}

// IdentityUniversalAuthStatus defines the observed state of IdentityUniversalAuth.
type IdentityUniversalAuthStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IdentityUniversalAuthObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IdentityUniversalAuth is the Schema for the IdentityUniversalAuths API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infisical}
type IdentityUniversalAuth struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IdentityUniversalAuthSpec   `json:"spec"`
	Status            IdentityUniversalAuthStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityUniversalAuthList contains a list of IdentityUniversalAuths
type IdentityUniversalAuthList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdentityUniversalAuth `json:"items"`
}

// Repository type metadata.
var (
	IdentityUniversalAuth_Kind             = "IdentityUniversalAuth"
	IdentityUniversalAuth_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IdentityUniversalAuth_Kind}.String()
	IdentityUniversalAuth_KindAPIVersion   = IdentityUniversalAuth_Kind + "." + CRDGroupVersion.String()
	IdentityUniversalAuth_GroupVersionKind = CRDGroupVersion.WithKind(IdentityUniversalAuth_Kind)
)

func init() {
	SchemeBuilder.Register(&IdentityUniversalAuth{}, &IdentityUniversalAuthList{})
}
