// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccessTokenTrustedIpsInitParameters struct {

	// (String)
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type AccessTokenTrustedIpsObservation struct {

	// (String)
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type AccessTokenTrustedIpsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`
}

type IdentityKubernetesAuthInitParameters struct {

	// (Number) The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// (Number) The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// (Number) The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (Attributes List) A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.. (see below for nested schema)
	AccessTokenTrustedIps []AccessTokenTrustedIpsInitParameters `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	// (String) An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	// An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	AllowedAudience *string `json:"allowedAudience,omitempty" tf:"allowed_audience,omitempty"`

	// (List of String) List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	// List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	AllowedNamespaces []*string `json:"allowedNamespaces,omitempty" tf:"allowed_namespaces,omitempty"`

	// (List of String) List of trusted service account names that are allowed to authenticate with Infisical.
	// List of trusted service account names that are allowed to authenticate with Infisical.
	AllowedServiceAccountNames []*string `json:"allowedServiceAccountNames,omitempty" tf:"allowed_service_account_names,omitempty"`

	// (String) Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	// Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// (String) The ID of the identity to attach the configuration onto.
	// The ID of the identity to attach the configuration onto.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	// The PEM-encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	KubernetesCACertificate *string `json:"kubernetesCaCertificate,omitempty" tf:"kubernetes_ca_certificate,omitempty"`

	// info.
	// The host string, host:port pair, or URL to the base of the Kubernetes API server. This can usually be obtained by running `kubectl cluster-info`.
	KubernetesHost *string `json:"kubernetesHost,omitempty" tf:"kubernetes_host,omitempty"`

	// lived service account JWT token for Infisical to access the TokenReview API to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	// A long-lived service account JWT token for Infisical to access the [TokenReview API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	TokenReviewerJwt *string `json:"tokenReviewerJwt,omitempty" tf:"token_reviewer_jwt,omitempty"`

	// (String) Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	// Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	TokenReviewerMode *string `json:"tokenReviewerMode,omitempty" tf:"token_reviewer_mode,omitempty"`
}

type IdentityKubernetesAuthObservation struct {

	// (Number) The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// (Number) The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// (Number) The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (Attributes List) A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.. (see below for nested schema)
	AccessTokenTrustedIps []AccessTokenTrustedIpsObservation `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	// (String) An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	// An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	AllowedAudience *string `json:"allowedAudience,omitempty" tf:"allowed_audience,omitempty"`

	// (List of String) List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	// List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	AllowedNamespaces []*string `json:"allowedNamespaces,omitempty" tf:"allowed_namespaces,omitempty"`

	// (List of String) List of trusted service account names that are allowed to authenticate with Infisical.
	// List of trusted service account names that are allowed to authenticate with Infisical.
	AllowedServiceAccountNames []*string `json:"allowedServiceAccountNames,omitempty" tf:"allowed_service_account_names,omitempty"`

	// (String) Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	// Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// (String) The ID of the kubernetes auth
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the identity to attach the configuration onto.
	// The ID of the identity to attach the configuration onto.
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	// The PEM-encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	KubernetesCACertificate *string `json:"kubernetesCaCertificate,omitempty" tf:"kubernetes_ca_certificate,omitempty"`

	// info.
	// The host string, host:port pair, or URL to the base of the Kubernetes API server. This can usually be obtained by running `kubectl cluster-info`.
	KubernetesHost *string `json:"kubernetesHost,omitempty" tf:"kubernetes_host,omitempty"`

	// lived service account JWT token for Infisical to access the TokenReview API to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	// A long-lived service account JWT token for Infisical to access the [TokenReview API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	TokenReviewerJwt *string `json:"tokenReviewerJwt,omitempty" tf:"token_reviewer_jwt,omitempty"`

	// (String) Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	// Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	TokenReviewerMode *string `json:"tokenReviewerMode,omitempty" tf:"token_reviewer_mode,omitempty"`
}

type IdentityKubernetesAuthParameters struct {

	// (Number) The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// +kubebuilder:validation:Optional
	AccessTokenMaxTTL *float64 `json:"accessTokenMaxTtl,omitempty" tf:"access_token_max_ttl,omitempty"`

	// (Number) The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	// The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
	// +kubebuilder:validation:Optional
	AccessTokenNumUsesLimit *float64 `json:"accessTokenNumUsesLimit,omitempty" tf:"access_token_num_uses_limit,omitempty"`

	// (Number) The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
	// +kubebuilder:validation:Optional
	AccessTokenTTL *float64 `json:"accessTokenTtl,omitempty" tf:"access_token_ttl,omitempty"`

	// (Attributes List) A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network address.. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AccessTokenTrustedIps []AccessTokenTrustedIpsParameters `json:"accessTokenTrustedIps,omitempty" tf:"access_token_trusted_ips,omitempty"`

	// (String) An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	// An optional audience claim that the service account JWT token must have to authenticate with Infisical.
	// +kubebuilder:validation:Optional
	AllowedAudience *string `json:"allowedAudience,omitempty" tf:"allowed_audience,omitempty"`

	// (List of String) List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	// List of trusted namespaces that service accounts must belong to authenticate with Infisical.
	// +kubebuilder:validation:Optional
	AllowedNamespaces []*string `json:"allowedNamespaces,omitempty" tf:"allowed_namespaces,omitempty"`

	// (List of String) List of trusted service account names that are allowed to authenticate with Infisical.
	// List of trusted service account names that are allowed to authenticate with Infisical.
	// +kubebuilder:validation:Optional
	AllowedServiceAccountNames []*string `json:"allowedServiceAccountNames,omitempty" tf:"allowed_service_account_names,omitempty"`

	// (String) Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	// Select a gateway for private cluster access. If not specified, the Internet Gateway will be used.
	// +kubebuilder:validation:Optional
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// (String) The ID of the identity to attach the configuration onto.
	// The ID of the identity to attach the configuration onto.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	// +kubebuilder:validation:Optional
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	// The PEM-encoded CA cert for the Kubernetes API server. This is used by the TLS client for secure communication with the Kubernetes API server.
	// +kubebuilder:validation:Optional
	KubernetesCACertificate *string `json:"kubernetesCaCertificate,omitempty" tf:"kubernetes_ca_certificate,omitempty"`

	// info.
	// The host string, host:port pair, or URL to the base of the Kubernetes API server. This can usually be obtained by running `kubectl cluster-info`.
	// +kubebuilder:validation:Optional
	KubernetesHost *string `json:"kubernetesHost,omitempty" tf:"kubernetes_host,omitempty"`

	// lived service account JWT token for Infisical to access the TokenReview API to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	// A long-lived service account JWT token for Infisical to access the [TokenReview API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) to validate other service account JWT tokens submitted by applications/pods. This is the JWT token obtained from step 1.5.
	// +kubebuilder:validation:Optional
	TokenReviewerJwt *string `json:"tokenReviewerJwt,omitempty" tf:"token_reviewer_jwt,omitempty"`

	// (String) Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	// Choose between Token ('api') or 'gateway' authentication. If using Gateway, the Gateway must be deployed in your Kubernetes cluster.
	// +kubebuilder:validation:Optional
	TokenReviewerMode *string `json:"tokenReviewerMode,omitempty" tf:"token_reviewer_mode,omitempty"`
}

// IdentityKubernetesAuthSpec defines the desired state of IdentityKubernetesAuth
type IdentityKubernetesAuthSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IdentityKubernetesAuthParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityKubernetesAuthInitParameters `json:"initProvider,omitempty"`
}

// IdentityKubernetesAuthStatus defines the observed state of IdentityKubernetesAuth.
type IdentityKubernetesAuthStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IdentityKubernetesAuthObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IdentityKubernetesAuth is the Schema for the IdentityKubernetesAuths API. Create and manage identity kubernetes auth in Infisical.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infisical}
type IdentityKubernetesAuth struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IdentityKubernetesAuthSpec   `json:"spec"`
	Status            IdentityKubernetesAuthStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityKubernetesAuthList contains a list of IdentityKubernetesAuths
type IdentityKubernetesAuthList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdentityKubernetesAuth `json:"items"`
}

// Repository type metadata.
var (
	IdentityKubernetesAuth_Kind             = "IdentityKubernetesAuth"
	IdentityKubernetesAuth_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IdentityKubernetesAuth_Kind}.String()
	IdentityKubernetesAuth_KindAPIVersion   = IdentityKubernetesAuth_Kind + "." + CRDGroupVersion.String()
	IdentityKubernetesAuth_GroupVersionKind = CRDGroupVersion.WithKind(IdentityKubernetesAuth_Kind)
)

func init() {
	SchemeBuilder.Register(&IdentityKubernetesAuth{}, &IdentityKubernetesAuthList{})
}
