// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IdentityUniversalAuthClientSecretInitParameters struct {

	// The description of the client secret.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the identity to create a client secret for
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// The maximum number of times that the client secret can be used; a value of 0 implies infinite number of uses. Default: 0
	NumberOfUsesLimit *float64 `json:"numberOfUsesLimit,omitempty" tf:"number_of_uses_limit,omitempty"`

	// The lifetime for the client secret in seconds. Default: 0 - not expiring
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type IdentityUniversalAuthClientSecretObservation struct {

	// The client ID of the secret.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The UTC timestamp of the created at date.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The description of the client secret.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the identity to create a client secret for
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// A flag indicating token has been revoked
	IsRevoked *bool `json:"isRevoked,omitempty" tf:"is_revoked,omitempty"`

	// The number of times that the client secret is used
	NumberOfUses *float64 `json:"numberOfUses,omitempty" tf:"number_of_uses,omitempty"`

	// The maximum number of times that the client secret can be used; a value of 0 implies infinite number of uses. Default: 0
	NumberOfUsesLimit *float64 `json:"numberOfUsesLimit,omitempty" tf:"number_of_uses_limit,omitempty"`

	// The lifetime for the client secret in seconds. Default: 0 - not expiring
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type IdentityUniversalAuthClientSecretParameters struct {

	// The description of the client secret.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the identity to create a client secret for
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	// +kubebuilder:validation:Optional
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// The maximum number of times that the client secret can be used; a value of 0 implies infinite number of uses. Default: 0
	// +kubebuilder:validation:Optional
	NumberOfUsesLimit *float64 `json:"numberOfUsesLimit,omitempty" tf:"number_of_uses_limit,omitempty"`

	// The lifetime for the client secret in seconds. Default: 0 - not expiring
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// IdentityUniversalAuthClientSecretSpec defines the desired state of IdentityUniversalAuthClientSecret
type IdentityUniversalAuthClientSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IdentityUniversalAuthClientSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityUniversalAuthClientSecretInitParameters `json:"initProvider,omitempty"`
}

// IdentityUniversalAuthClientSecretStatus defines the observed state of IdentityUniversalAuthClientSecret.
type IdentityUniversalAuthClientSecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IdentityUniversalAuthClientSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IdentityUniversalAuthClientSecret is the Schema for the IdentityUniversalAuthClientSecrets API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infisical}
type IdentityUniversalAuthClientSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IdentityUniversalAuthClientSecretSpec   `json:"spec"`
	Status            IdentityUniversalAuthClientSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityUniversalAuthClientSecretList contains a list of IdentityUniversalAuthClientSecrets
type IdentityUniversalAuthClientSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdentityUniversalAuthClientSecret `json:"items"`
}

// Repository type metadata.
var (
	IdentityUniversalAuthClientSecret_Kind             = "IdentityUniversalAuthClientSecret"
	IdentityUniversalAuthClientSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IdentityUniversalAuthClientSecret_Kind}.String()
	IdentityUniversalAuthClientSecret_KindAPIVersion   = IdentityUniversalAuthClientSecret_Kind + "." + CRDGroupVersion.String()
	IdentityUniversalAuthClientSecret_GroupVersionKind = CRDGroupVersion.WithKind(IdentityUniversalAuthClientSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&IdentityUniversalAuthClientSecret{}, &IdentityUniversalAuthClientSecretList{})
}
