apiVersion: project.infisical.m.hangar.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: gcp-project
  name: gcp-project
  namespace: crossplane-system
spec:
  forProvider:
    description: This is a GCP project
    name: GCP Project
    slug: gcp-project
    type: secret-manager
