// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ProjectInitParameters struct {

	// (Number) The audit log retention in days
	// The audit log retention in days
	AuditLogRetentionDays *float64 `json:"auditLogRetentionDays,omitempty" tf:"audit_log_retention_days,omitempty"`

	// (String) The description of the project
	// The description of the project
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the project has delete protection, defaults to false
	// Whether the project has delete protection, defaults to false
	HasDeleteProtection *bool `json:"hasDeleteProtection,omitempty" tf:"has_delete_protection,omitempty"`

	// (String) The ID of the KMS secret manager key to use for the project
	// The ID of the KMS secret manager key to use for the project
	KMSSecretManagerKeyID *string `json:"kmsSecretManagerKeyId,omitempty" tf:"kms_secret_manager_key_id,omitempty"`

	// (String) The name of the project
	// The name of the project
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to create default environments for the project (dev, staging, prod), defaults to true
	// Whether to create default environments for the project (dev, staging, prod), defaults to true
	ShouldCreateDefaultEnvs *bool `json:"shouldCreateDefaultEnvs,omitempty" tf:"should_create_default_envs,omitempty"`

	// (String) The slug of the project
	// The slug of the project
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) The name of the template to use for the project
	// The name of the template to use for the project
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// manager, cert-manager, kms. Defaults to 'secret-manager'.
	// The type of the project. Supported values: secret-manager, cert-manager, kms. Defaults to 'secret-manager'.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectObservation struct {

	// (Number) The audit log retention in days
	// The audit log retention in days
	AuditLogRetentionDays *float64 `json:"auditLogRetentionDays,omitempty" tf:"audit_log_retention_days,omitempty"`

	// (String) The description of the project
	// The description of the project
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the project has delete protection, defaults to false
	// Whether the project has delete protection, defaults to false
	HasDeleteProtection *bool `json:"hasDeleteProtection,omitempty" tf:"has_delete_protection,omitempty"`

	// (String) The ID of the project
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the KMS secret manager key to use for the project
	// The ID of the KMS secret manager key to use for the project
	KMSSecretManagerKeyID *string `json:"kmsSecretManagerKeyId,omitempty" tf:"kms_secret_manager_key_id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The name of the project
	// The name of the project
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to create default environments for the project (dev, staging, prod), defaults to true
	// Whether to create default environments for the project (dev, staging, prod), defaults to true
	ShouldCreateDefaultEnvs *bool `json:"shouldCreateDefaultEnvs,omitempty" tf:"should_create_default_envs,omitempty"`

	// (String) The slug of the project
	// The slug of the project
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) The name of the template to use for the project
	// The name of the template to use for the project
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// manager, cert-manager, kms. Defaults to 'secret-manager'.
	// The type of the project. Supported values: secret-manager, cert-manager, kms. Defaults to 'secret-manager'.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectParameters struct {

	// (Number) The audit log retention in days
	// The audit log retention in days
	// +kubebuilder:validation:Optional
	AuditLogRetentionDays *float64 `json:"auditLogRetentionDays,omitempty" tf:"audit_log_retention_days,omitempty"`

	// (String) The description of the project
	// The description of the project
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the project has delete protection, defaults to false
	// Whether the project has delete protection, defaults to false
	// +kubebuilder:validation:Optional
	HasDeleteProtection *bool `json:"hasDeleteProtection,omitempty" tf:"has_delete_protection,omitempty"`

	// (String) The ID of the KMS secret manager key to use for the project
	// The ID of the KMS secret manager key to use for the project
	// +kubebuilder:validation:Optional
	KMSSecretManagerKeyID *string `json:"kmsSecretManagerKeyId,omitempty" tf:"kms_secret_manager_key_id,omitempty"`

	// (String) The name of the project
	// The name of the project
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to create default environments for the project (dev, staging, prod), defaults to true
	// Whether to create default environments for the project (dev, staging, prod), defaults to true
	// +kubebuilder:validation:Optional
	ShouldCreateDefaultEnvs *bool `json:"shouldCreateDefaultEnvs,omitempty" tf:"should_create_default_envs,omitempty"`

	// (String) The slug of the project
	// The slug of the project
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) The name of the template to use for the project
	// The name of the template to use for the project
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// manager, cert-manager, kms. Defaults to 'secret-manager'.
	// The type of the project. Supported values: secret-manager, cert-manager, kms. Defaults to 'secret-manager'.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. Create projects & save to Infisical. Only Machine Identity authentication is supported for this data source.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infisical}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
