// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IdentityInitParameters struct {
}

type IdentityObservation struct {

	// (List of String) The auth methods for the identity
	// The auth methods for the identity
	AuthMethods []*string `json:"authMethods,omitempty" tf:"auth_methods,omitempty"`

	// (String) The ID of the project identity role.
	// The ID of the identity
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the identity
	// The name of the identity
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IdentityParameters struct {
}

type ProjectIdentityInitParameters struct {

	// added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	// When true, if the identity is already a member of the project (e.g. auto-added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	AdoptExisting *bool `json:"adoptExisting,omitempty" tf:"adopt_existing,omitempty"`

	// (String) The id of the identity.
	// The id of the identity.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// (String) The id of the project
	// The id of the project
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes List) The roles assigned to the project identity (see below for nested schema)
	Roles []RolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`
}

type ProjectIdentityObservation struct {

	// added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	// When true, if the identity is already a member of the project (e.g. auto-added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	AdoptExisting *bool `json:"adoptExisting,omitempty" tf:"adopt_existing,omitempty"`

	// (String) The ID of the project identity role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) The identity details of the project identity (see below for nested schema)
	Identity *IdentityObservation `json:"identity,omitempty" tf:"identity,omitempty"`

	// (String) The id of the identity.
	// The id of the identity.
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// (String) The membership Id of the project identity
	// The membership Id of the project identity
	MembershipID *string `json:"membershipId,omitempty" tf:"membership_id,omitempty"`

	// (String) The id of the project
	// The id of the project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes List) The roles assigned to the project identity (see below for nested schema)
	Roles []RolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`
}

type ProjectIdentityParameters struct {

	// added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	// When true, if the identity is already a member of the project (e.g. auto-added by Infisical when the project was created by this identity), the existing membership is adopted and its roles are updated to match the desired state instead of returning an error. Defaults to false.
	// +kubebuilder:validation:Optional
	AdoptExisting *bool `json:"adoptExisting,omitempty" tf:"adopt_existing,omitempty"`

	// (String) The id of the identity.
	// The id of the identity.
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/identity/v1alpha1.Identity
	// +kubebuilder:validation:Optional
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// Reference to a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDRef *v2.NamespacedReference `json:"identityIdRef,omitempty" tf:"-"`

	// Selector for a Identity in identity to populate identityId.
	// +kubebuilder:validation:Optional
	IdentityIDSelector *v2.NamespacedSelector `json:"identityIdSelector,omitempty" tf:"-"`

	// (String) The id of the project
	// The id of the project
	// +crossplane:generate:reference:type=github.com/jfillman/provider-infisical/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes List) The roles assigned to the project identity (see below for nested schema)
	// +kubebuilder:validation:Optional
	Roles []RolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`
}

type RolesInitParameters struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type RolesObservation struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (String) The ID of the project identity role.
	// The ID of the project identity role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type RolesParameters struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	// +kubebuilder:validation:Optional
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// +kubebuilder:validation:Optional
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	// +kubebuilder:validation:Optional
	RoleSlug *string `json:"roleSlug" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// +kubebuilder:validation:Optional
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	// +kubebuilder:validation:Optional
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	// +kubebuilder:validation:Optional
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// +kubebuilder:validation:Optional
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

// ProjectIdentitySpec defines the desired state of ProjectIdentity
type ProjectIdentitySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectIdentityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectIdentityInitParameters `json:"initProvider,omitempty"`
}

// ProjectIdentityStatus defines the observed state of ProjectIdentity.
type ProjectIdentityStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectIdentityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectIdentity is the Schema for the ProjectIdentitys API. Assign an existing organization-level machine identity to a project & save to Infisical. This resource does not create a new identity; it manages the project membership and role(s) of an identity that already exists at the organization level. To create an identity that lives inside a single project, use the infisical_project_scoped_identity resource instead. Only Machine Identity authentication is supported for this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infisical}
type ProjectIdentity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	Spec   ProjectIdentitySpec   `json:"spec"`
	Status ProjectIdentityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectIdentityList contains a list of ProjectIdentitys
type ProjectIdentityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectIdentity `json:"items"`
}

// Repository type metadata.
var (
	ProjectIdentity_Kind             = "ProjectIdentity"
	ProjectIdentity_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectIdentity_Kind}.String()
	ProjectIdentity_KindAPIVersion   = ProjectIdentity_Kind + "." + CRDGroupVersion.String()
	ProjectIdentity_GroupVersionKind = CRDGroupVersion.WithKind(ProjectIdentity_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectIdentity{}, &ProjectIdentityList{})
}
